"""
Django settings for sophomore project.

Generated by 'django-admin startproject' using Django 3.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os, sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ck-a5-ri3m_s!2t-#6(%u^qe-%o)*q)7ypdb(1zqvw&xt2$ew3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'personal',
    'operation',
    'rbac',
    'assets',

    'widget_tweaks',  #
    'django_filters',  # 自定义过滤字段
    'django_tables2',  # 自定义表格显示字段
    'import_export'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sophomore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sophomore.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': os.path.dirname(os.path.abspath(__file__)) + '/mysql.cnf'
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

USE_TZ = True  # 默认值True。
TIME_ZONE = 'Asia/Shanghai'  # 设置时区
USE_I18N = True  # 默认为True，是否启用自动翻译系统
USE_L10N = True  # 默认False，以本地化格式显示数字和时间

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# 单个静态文件夹
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 多个静态文件夹注册
STATICFILES_DIRS = [
    # 第一个静态文件夹
    os.path.join(BASE_DIR, 'static'),
    # 第二个静态文件夹
    # "/home/user/pictures",

]

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
AUTH_USER_MODEL = 'rbac.UserProfile'

SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# SIMPLEUI_CONFIG = {
#     # 是否使用系统默认菜单，自定义菜单时建议关闭。
#     'system_keep': False,
#
#     # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
#     'menu_display': ['任务管理', '权限管理'],
#
#     # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
#     # 一般建议关闭。
#     'dynamic': False,
#     'menus': [
#         {
#             'app': 'rbac',
#             'name': '权限管理',
#             'icon': 'fas fa-user-shield',
#             'models': [
#                 {
#                     'name': '用户列表',
#                     'icon': 'fa fa-user',
#                     'url': 'rbac/user/'
#                 },
#                 {
#                     'name': '用户组',
#                     'icon': 'fa fa-th-list',
#                     'url': 'rbac/group/'
#                 }
#             ]
#         },
#
#         {
#             'name': '任务管理',
#             'icon': 'fa fa-th-list',
#             'models': [
#                 {
#                     'name': '任务列表',
#                     # 注意url按'/admin/应用名小写/模型名小写/'命名。
#                     'url': '/admin/tasks/task/',
#                     'icon': 'fa fa-tasks'
#                 },
#             ]
#         },
#     ]
# }
