# Generated by Django 3.1.13 on 2021-09-08 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DbRecoveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnvCreateOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FaultResolveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='工单号', max_length=30, unique=True, verbose_name='工单号')),
                ('title', models.CharField(help_text='工单标题', max_length=30, unique=True, verbose_name='工单标题')),
                ('content', models.CharField(help_text='工单内容', max_length=30, unique=True, verbose_name='工单内容')),
                ('type', models.CharField(choices=[('1', '待提交'), ('2', '待审核'), ('3', '执行中'), ('4', '待脱敏'), ('5', '脱敏中'), ('6', '已脱敏'), ('7', '待确认'), ('8', '已关闭')], default='0', help_text='工单类型', max_length=30, verbose_name='工单类型')),
                ('status', models.CharField(choices=[('1', '待提交'), ('2', '待审核'), ('3', '执行中'), ('4', '待脱敏'), ('5', '脱敏中'), ('6', '已脱敏'), ('7', '待确认'), ('8', '已关闭')], default='0', help_text='工单状态', max_length=30, verbose_name='工单状态')),
                ('is_show', models.BooleanField(blank=True, default=True, verbose_name='是否显示')),
                ('is_return', models.BooleanField(blank=True, default=True, verbose_name='是否退回')),
                ('add_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('expect_time', models.DateTimeField(blank=True, null=True, verbose_name='期望时间')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('target_time', models.DateTimeField(blank=True, null=True, verbose_name='目标时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('proposer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposer', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('todoer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todoer', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人')),
            ],
        ),
    ]
